dir: .
structname: '{{.InterfaceName}}'
pkgname: aferomock
filename: "{{ .InterfaceName | snakecase }}.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/spf13/afero:
    config:
      include-interface-regex: Fs|File
  io/fs:
    config:
      include-interface-regex: FileInfo
