// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: https://github.com/nhatthm/mockery-template

package aferomock

import (
	"os"
	"slices"
	"testing"

	mock "github.com/stretchr/testify/mock"
)

// NopFile is a File mock with no expectation.
var NopFile = MockFile()

// FileMocker is a func that creates a File mock. It is used to compose
// mock expectations from other packages without exposing *testing.T.
type FileMocker func(tb testing.TB) *File

var defaultFileMocks []func(file *File)

// SetFileDefaultMocks sets the default mocks for File.
func SetFileDefaultMocks(mocks ...func(file *File)) {
	defaultFileMocks = mocks
}

// AppendFileDefaultMock appends a new mock to the default mocks for File.
func AppendFileDefaultMock(mock func(file *File)) {
	defaultFileMocks = append(defaultFileMocks, mock)
}

// MockFile creates a new File mock with cleanup to ensure all the expectations are met.
func MockFile(mocks ...func(file *File)) FileMocker {
	return func(tb testing.TB) *File {
		tb.Helper()

		file := NewFile(tb)
		for _, configure := range slices.Concat(defaultFileMocks, mocks) {
			configure(file)
		}

		return file
	}
}

// NewFile creates a new instance of File. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *File {
	mock := &File{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// File is an autogenerated mock type for the File type
type File struct {
	mock.Mock
}

type File_Expecter struct {
	mock *mock.Mock
}

func (_m *File) EXPECT() *File_Expecter {
	return &File_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type File
func (_mock *File) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// File_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type File_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *File_Expecter) Close() *File_Close_Call {
	return &File_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *File_Close_Call) Run(run func()) *File_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_Close_Call) Return(err error) *File_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *File_Close_Call) RunAndReturn(run func() error) *File_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type File
func (_mock *File) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// File_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type File_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *File_Expecter) Name() *File_Name_Call {
	return &File_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *File_Name_Call) Run(run func()) *File_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_Name_Call) Return(s string) *File_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *File_Name_Call) RunAndReturn(run func() string) *File_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type File
func (_mock *File) Read(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type File_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *File_Expecter) Read(p any) *File_Read_Call {
	return &File_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *File_Read_Call) Run(run func(p []byte)) *File_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_Read_Call) Return(n int, err error) *File_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_Read_Call) RunAndReturn(run func(p []byte) (int, error)) *File_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function for the type File
func (_mock *File) ReadAt(p []byte, off int64) (int, error) {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return returnFunc(p, off)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = returnFunc(p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type File_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *File_Expecter) ReadAt(p any, off any) *File_ReadAt_Call {
	return &File_ReadAt_Call{Call: _e.mock.On("ReadAt", p, off)}
}

func (_c *File_ReadAt_Call) Run(run func(p []byte, off int64)) *File_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *File_ReadAt_Call) Return(n int, err error) *File_ReadAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_ReadAt_Call) RunAndReturn(run func(p []byte, off int64) (int, error)) *File_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// Readdir provides a mock function for the type File
func (_mock *File) Readdir(count int) ([]os.FileInfo, error) {
	ret := _mock.Called(count)

	if len(ret) == 0 {
		panic("no return value specified for Readdir")
	}

	var r0 []os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]os.FileInfo, error)); ok {
		return returnFunc(count)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []os.FileInfo); ok {
		r0 = returnFunc(count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Readdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readdir'
type File_Readdir_Call struct {
	*mock.Call
}

// Readdir is a helper method to define mock.On call
//   - count int
func (_e *File_Expecter) Readdir(count any) *File_Readdir_Call {
	return &File_Readdir_Call{Call: _e.mock.On("Readdir", count)}
}

func (_c *File_Readdir_Call) Run(run func(count int)) *File_Readdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_Readdir_Call) Return(fileInfos []os.FileInfo, err error) *File_Readdir_Call {
	_c.Call.Return(fileInfos, err)
	return _c
}

func (_c *File_Readdir_Call) RunAndReturn(run func(count int) ([]os.FileInfo, error)) *File_Readdir_Call {
	_c.Call.Return(run)
	return _c
}

// Readdirnames provides a mock function for the type File
func (_mock *File) Readdirnames(n int) ([]string, error) {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Readdirnames")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]string, error)); ok {
		return returnFunc(n)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []string); ok {
		r0 = returnFunc(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Readdirnames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readdirnames'
type File_Readdirnames_Call struct {
	*mock.Call
}

// Readdirnames is a helper method to define mock.On call
//   - n int
func (_e *File_Expecter) Readdirnames(n any) *File_Readdirnames_Call {
	return &File_Readdirnames_Call{Call: _e.mock.On("Readdirnames", n)}
}

func (_c *File_Readdirnames_Call) Run(run func(n int)) *File_Readdirnames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_Readdirnames_Call) Return(strings []string, err error) *File_Readdirnames_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *File_Readdirnames_Call) RunAndReturn(run func(n int) ([]string, error)) *File_Readdirnames_Call {
	_c.Call.Return(run)
	return _c
}

// Seek provides a mock function for the type File
func (_mock *File) Seek(offset int64, whence int) (int64, error) {
	ret := _mock.Called(offset, whence)

	if len(ret) == 0 {
		panic("no return value specified for Seek")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) (int64, error)); ok {
		return returnFunc(offset, whence)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int) int64); ok {
		r0 = returnFunc(offset, whence)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = returnFunc(offset, whence)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Seek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seek'
type File_Seek_Call struct {
	*mock.Call
}

// Seek is a helper method to define mock.On call
//   - offset int64
//   - whence int
func (_e *File_Expecter) Seek(offset any, whence any) *File_Seek_Call {
	return &File_Seek_Call{Call: _e.mock.On("Seek", offset, whence)}
}

func (_c *File_Seek_Call) Run(run func(offset int64, whence int)) *File_Seek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *File_Seek_Call) Return(n int64, err error) *File_Seek_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_Seek_Call) RunAndReturn(run func(offset int64, whence int) (int64, error)) *File_Seek_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type File
func (_mock *File) Stat() (os.FileInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (os.FileInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() os.FileInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type File_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
func (_e *File_Expecter) Stat() *File_Stat_Call {
	return &File_Stat_Call{Call: _e.mock.On("Stat")}
}

func (_c *File_Stat_Call) Run(run func()) *File_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_Stat_Call) Return(fileInfo os.FileInfo, err error) *File_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *File_Stat_Call) RunAndReturn(run func() (os.FileInfo, error)) *File_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type File
func (_mock *File) Sync() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// File_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type File_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
func (_e *File_Expecter) Sync() *File_Sync_Call {
	return &File_Sync_Call{Call: _e.mock.On("Sync")}
}

func (_c *File_Sync_Call) Run(run func()) *File_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *File_Sync_Call) Return(err error) *File_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *File_Sync_Call) RunAndReturn(run func() error) *File_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// Truncate provides a mock function for the type File
func (_mock *File) Truncate(size int64) error {
	ret := _mock.Called(size)

	if len(ret) == 0 {
		panic("no return value specified for Truncate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// File_Truncate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Truncate'
type File_Truncate_Call struct {
	*mock.Call
}

// Truncate is a helper method to define mock.On call
//   - size int64
func (_e *File_Expecter) Truncate(size any) *File_Truncate_Call {
	return &File_Truncate_Call{Call: _e.mock.On("Truncate", size)}
}

func (_c *File_Truncate_Call) Run(run func(size int64)) *File_Truncate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_Truncate_Call) Return(err error) *File_Truncate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *File_Truncate_Call) RunAndReturn(run func(size int64) error) *File_Truncate_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type File
func (_mock *File) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type File_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *File_Expecter) Write(p any) *File_Write_Call {
	return &File_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *File_Write_Call) Run(run func(p []byte)) *File_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_Write_Call) Return(n int, err error) *File_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *File_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAt provides a mock function for the type File
func (_mock *File) WriteAt(p []byte, off int64) (int, error) {
	ret := _mock.Called(p, off)

	if len(ret) == 0 {
		panic("no return value specified for WriteAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) (int, error)); ok {
		return returnFunc(p, off)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int64) int); ok {
		r0 = returnFunc(p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int64) error); ok {
		r1 = returnFunc(p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// File_WriteAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAt'
type File_WriteAt_Call struct {
	*mock.Call
}

// WriteAt is a helper method to define mock.On call
//   - p []byte
//   - off int64
func (_e *File_Expecter) WriteAt(p any, off any) *File_WriteAt_Call {
	return &File_WriteAt_Call{Call: _e.mock.On("WriteAt", p, off)}
}

func (_c *File_WriteAt_Call) Run(run func(p []byte, off int64)) *File_WriteAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *File_WriteAt_Call) Return(n int, err error) *File_WriteAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *File_WriteAt_Call) RunAndReturn(run func(p []byte, off int64) (int, error)) *File_WriteAt_Call {
	_c.Call.Return(run)
	return _c
}

// WriteString provides a mock function for the type File
func (_mock *File) WriteString(s string) (int, error) {
	ret1 := _mock.Called(s)

	if len(ret1) == 0 {
		panic("no return value specified for WriteString")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret1.Get(0).(func(string) (int, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret1.Get(0).(func(string) int); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret1.Get(0).(int)
	}
	if returnFunc, ok := ret1.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret1.Error(1)
	}
	return r0, r1
}

// File_WriteString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteString'
type File_WriteString_Call struct {
	*mock.Call
}

// WriteString is a helper method to define mock.On call
//   - s string
func (_e *File_Expecter) WriteString(s any) *File_WriteString_Call {
	return &File_WriteString_Call{Call: _e.mock.On("WriteString", s)}
}

func (_c *File_WriteString_Call) Run(run func(s string)) *File_WriteString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *File_WriteString_Call) Return(ret int, err error) *File_WriteString_Call {
	_c.Call.Return(ret, err)
	return _c
}

func (_c *File_WriteString_Call) RunAndReturn(run func(s string) (int, error)) *File_WriteString_Call {
	_c.Call.Return(run)
	return _c
}
