// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package aferomock

import (
	"os"
	"time"

	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewFs creates a new instance of Fs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFs(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fs {
	mock := &Fs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Fs is an autogenerated mock type for the Fs type
type Fs struct {
	mock.Mock
}

type Fs_Expecter struct {
	mock *mock.Mock
}

func (_m *Fs) EXPECT() *Fs_Expecter {
	return &Fs_Expecter{mock: &_m.Mock}
}

// Chmod provides a mock function for the type Fs
func (_mock *Fs) Chmod(name string, mode os.FileMode) error {
	ret := _mock.Called(name, mode)

	if len(ret) == 0 {
		panic("no return value specified for Chmod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(name, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fs_Chmod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chmod'
type Fs_Chmod_Call struct {
	*mock.Call
}

// Chmod is a helper method to define mock.On call
//   - name string
//   - mode os.FileMode
func (_e *Fs_Expecter) Chmod(name any, mode any) *Fs_Chmod_Call {
	return &Fs_Chmod_Call{Call: _e.mock.On("Chmod", name, mode)}
}

func (_c *Fs_Chmod_Call) Run(run func(name string, mode os.FileMode)) *Fs_Chmod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Fs_Chmod_Call) Return(err error) *Fs_Chmod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fs_Chmod_Call) RunAndReturn(run func(name string, mode os.FileMode) error) *Fs_Chmod_Call {
	_c.Call.Return(run)
	return _c
}

// Chown provides a mock function for the type Fs
func (_mock *Fs) Chown(name string, uid int, gid int) error {
	ret := _mock.Called(name, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for Chown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) error); ok {
		r0 = returnFunc(name, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fs_Chown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chown'
type Fs_Chown_Call struct {
	*mock.Call
}

// Chown is a helper method to define mock.On call
//   - name string
//   - uid int
//   - gid int
func (_e *Fs_Expecter) Chown(name any, uid any, gid any) *Fs_Chown_Call {
	return &Fs_Chown_Call{Call: _e.mock.On("Chown", name, uid, gid)}
}

func (_c *Fs_Chown_Call) Run(run func(name string, uid int, gid int)) *Fs_Chown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Fs_Chown_Call) Return(err error) *Fs_Chown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fs_Chown_Call) RunAndReturn(run func(name string, uid int, gid int) error) *Fs_Chown_Call {
	_c.Call.Return(run)
	return _c
}

// Chtimes provides a mock function for the type Fs
func (_mock *Fs) Chtimes(name string, atime time.Time, mtime time.Time) error {
	ret := _mock.Called(name, atime, mtime)

	if len(ret) == 0 {
		panic("no return value specified for Chtimes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time, time.Time) error); ok {
		r0 = returnFunc(name, atime, mtime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fs_Chtimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chtimes'
type Fs_Chtimes_Call struct {
	*mock.Call
}

// Chtimes is a helper method to define mock.On call
//   - name string
//   - atime time.Time
//   - mtime time.Time
func (_e *Fs_Expecter) Chtimes(name any, atime any, mtime any) *Fs_Chtimes_Call {
	return &Fs_Chtimes_Call{Call: _e.mock.On("Chtimes", name, atime, mtime)}
}

func (_c *Fs_Chtimes_Call) Run(run func(name string, atime time.Time, mtime time.Time)) *Fs_Chtimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Fs_Chtimes_Call) Return(err error) *Fs_Chtimes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fs_Chtimes_Call) RunAndReturn(run func(name string, atime time.Time, mtime time.Time) error) *Fs_Chtimes_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type Fs
func (_mock *Fs) Create(name string) (afero.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (afero.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) afero.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Fs_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Fs_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *Fs_Expecter) Create(name any) *Fs_Create_Call {
	return &Fs_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *Fs_Create_Call) Run(run func(name string)) *Fs_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Fs_Create_Call) Return(file afero.File, err error) *Fs_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *Fs_Create_Call) RunAndReturn(run func(name string) (afero.File, error)) *Fs_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Mkdir provides a mock function for the type Fs
func (_mock *Fs) Mkdir(name string, perm os.FileMode) error {
	ret := _mock.Called(name, perm)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(name, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fs_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type Fs_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - name string
//   - perm os.FileMode
func (_e *Fs_Expecter) Mkdir(name any, perm any) *Fs_Mkdir_Call {
	return &Fs_Mkdir_Call{Call: _e.mock.On("Mkdir", name, perm)}
}

func (_c *Fs_Mkdir_Call) Run(run func(name string, perm os.FileMode)) *Fs_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Fs_Mkdir_Call) Return(err error) *Fs_Mkdir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fs_Mkdir_Call) RunAndReturn(run func(name string, perm os.FileMode) error) *Fs_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type Fs
func (_mock *Fs) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fs_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type Fs_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *Fs_Expecter) MkdirAll(path any, perm any) *Fs_MkdirAll_Call {
	return &Fs_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *Fs_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *Fs_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Fs_MkdirAll_Call) Return(err error) *Fs_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fs_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *Fs_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type Fs
func (_mock *Fs) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Fs_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Fs_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Fs_Expecter) Name() *Fs_Name_Call {
	return &Fs_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Fs_Name_Call) Run(run func()) *Fs_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Fs_Name_Call) Return(s string) *Fs_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Fs_Name_Call) RunAndReturn(run func() string) *Fs_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type Fs
func (_mock *Fs) Open(name string) (afero.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (afero.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) afero.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Fs_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type Fs_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *Fs_Expecter) Open(name any) *Fs_Open_Call {
	return &Fs_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *Fs_Open_Call) Run(run func(name string)) *Fs_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Fs_Open_Call) Return(file afero.File, err error) *Fs_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *Fs_Open_Call) RunAndReturn(run func(name string) (afero.File, error)) *Fs_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function for the type Fs
func (_mock *Fs) OpenFile(name string, flag int, perm os.FileMode) (afero.File, error) {
	ret := _mock.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 afero.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) (afero.File, error)); ok {
		return returnFunc(name, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) afero.File); ok {
		r0 = returnFunc(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, os.FileMode) error); ok {
		r1 = returnFunc(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Fs_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type Fs_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - name string
//   - flag int
//   - perm os.FileMode
func (_e *Fs_Expecter) OpenFile(name any, flag any, perm any) *Fs_OpenFile_Call {
	return &Fs_OpenFile_Call{Call: _e.mock.On("OpenFile", name, flag, perm)}
}

func (_c *Fs_OpenFile_Call) Run(run func(name string, flag int, perm os.FileMode)) *Fs_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Fs_OpenFile_Call) Return(file afero.File, err error) *Fs_OpenFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *Fs_OpenFile_Call) RunAndReturn(run func(name string, flag int, perm os.FileMode) (afero.File, error)) *Fs_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type Fs
func (_mock *Fs) Remove(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fs_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Fs_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name string
func (_e *Fs_Expecter) Remove(name any) *Fs_Remove_Call {
	return &Fs_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *Fs_Remove_Call) Run(run func(name string)) *Fs_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Fs_Remove_Call) Return(err error) *Fs_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fs_Remove_Call) RunAndReturn(run func(name string) error) *Fs_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type Fs
func (_mock *Fs) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fs_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type Fs_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *Fs_Expecter) RemoveAll(path any) *Fs_RemoveAll_Call {
	return &Fs_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *Fs_RemoveAll_Call) Run(run func(path string)) *Fs_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Fs_RemoveAll_Call) Return(err error) *Fs_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fs_RemoveAll_Call) RunAndReturn(run func(path string) error) *Fs_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type Fs
func (_mock *Fs) Rename(oldname string, newname string) error {
	ret := _mock.Called(oldname, newname)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldname, newname)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fs_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type Fs_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - oldname string
//   - newname string
func (_e *Fs_Expecter) Rename(oldname any, newname any) *Fs_Rename_Call {
	return &Fs_Rename_Call{Call: _e.mock.On("Rename", oldname, newname)}
}

func (_c *Fs_Rename_Call) Run(run func(oldname string, newname string)) *Fs_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Fs_Rename_Call) Return(err error) *Fs_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fs_Rename_Call) RunAndReturn(run func(oldname string, newname string) error) *Fs_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type Fs
func (_mock *Fs) Stat(name string) (os.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Fs_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type Fs_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *Fs_Expecter) Stat(name any) *Fs_Stat_Call {
	return &Fs_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *Fs_Stat_Call) Run(run func(name string)) *Fs_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Fs_Stat_Call) Return(fileInfo os.FileInfo, err error) *Fs_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *Fs_Stat_Call) RunAndReturn(run func(name string) (os.FileInfo, error)) *Fs_Stat_Call {
	_c.Call.Return(run)
	return _c
}
